pipeline {
    agent any

    environment {
        SONAR_PROJECT_KEY = 'eflow-frontend'
        S3_BUCKET         = 'eflow-frontend-bucket'
        CF_DIST_ID        =  E2PZMYBHBCKH1B
        AWS_REGION        = 'ap-south-1'
        BUILD_DIR         = 'dist'
    }

    tools {
        nodejs 'NodeJS-18'
    }

    stages {

        stage('1 - GitHub Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'git-cred',
                    url: 'https://github.com/peakyblinder0509/E-flow-cicdpipeline1.git'
            }
        }

        stage('2 - Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('3 - Build Frontend') {
            steps {
                sh 'npm run build'
            }
        }

        stage('4 - SonarQube Scan') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh """
                        npx sonar-scanner \
                          -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                          -Dsonar.sources=src
                    """
                }
            }
        }

        stage('5 - SonarQube Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('6 - Deploy to S3') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',
                                  credentialsId: 'aws-crd']]) {
                    sh """
                        aws s3 sync ${BUILD_DIR}/ s3://${S3_BUCKET}/ \
                          --region ${AWS_REGION} \
                          --delete
                    """
                }
            }
        }

        stage('7 - CloudFront Invalidation') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',
                                  credentialsId: 'aws-crd']]) {
                    sh """
                        aws cloudfront create-invalidation \
                          --distribution-id ${CF_DIST_ID} \
                          --paths "*"
                    """
                }
            }
        }
    }

    post {
        success {
            echo  'Frontend deployed successfully to S3 + CloudFront!'
        }
        failure {
            echo  'Frontend pipeline failed! Check logs.'
        }
    }
}
